[workspace]
members = [
  "crates/domain",
  "crates/backend_pacman",
  "crates/backend_aur",
  "crates/app_ui",
  "crates/app_shell",
]
resolver = "3"

[workspace.package]
version = "0.3.3"
edition = "2024"

[workspace.dependencies]
crossbeam-channel = "0.5.15"
thiserror = "2"
parking_lot = "0.12"
anyhow = "1"
env_logger = "0.11"
regex = "1.12"
nix = { version = "0.31", default-features = false, features = ["signal"] }
ureq = { version = "3", features = ["json"] }
serde = { version = "1", features = ["derive"] }
urlencoding = "2"
tempfile = "3"
notify = "8"
log = "0.4"
repose-ui = "0.16.0"
repose-core = "0.16.0"
repose-platform = { version = "0.16.0", features = ["desktop"] }
repose-material = "0.16.0"


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

# [patch.crates-io]
# repose-core = { path = "../repose/crates/repose-core" }
# repose-ui = { path = "../repose/crates/repose-ui" }
# repose-platform = { path = "../repose/crates/repose-platform" }
# repose-material = { path = "../repose/crates/repose-material" }
