[package]
name = "backend_aur"
version.workspace = true
edition.workspace = true

[dependencies]
domain = { path = "../domain" }
ureq.workspace = true
serde.workspace = true
urlencoding.workspace = true
tempfile.workspace = true
log.workspace = true
alpm.workspace = true
serde_json.workspace = true
similar.workspace = true
