[package]
name = "backend_pacman"
version.workspace = true
edition.workspace = true

[dependencies]
domain = { path = "../domain" }
nix.workspace = true
parking_lot.workspace = true
alpm-db.workspace = true
alpm-repo-db.workspace = true
alpm-types.workspace = true
flate2.workspace = true
tar.workspace = true
