[package]
name = "app_shell"
version.workspace = true
edition.workspace = true

# [package.metadata.android]
# package = "org.mlm.soredowe"
# label = "Soredowe"
# build_targets = ["aarch64-linux-android"]

# [package.metadata.android.sdk]
# min_sdk_version = 29
# target_sdk_version = 36

[dependencies]
repose-platform.workspace = true
repose-ui.workspace = true
repose-core.workspace = true
crossbeam-channel.workspace = true
anyhow.workspace = true
env_logger.workspace = true
domain = { path = "../domain" }
backend_pacman = { path = "../backend_pacman" }
backend_aur = { path = "../backend_aur" }
app_ui = { path = "../app_ui" }
notify.workspace = true
log.workspace = true
