name: Release binaries

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      upload_releases:
        description: "Upload releases"
        required: true
        default: true
        type: boolean
      mark_prerelease:
        description: "Mark as prerelease"
        required: true
        default: false
        type: boolean
      bump_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - none
          - patch
          - minor
          - major

concurrency:
  group: release-bin-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: mlm-games/ci/.github/workflows/rust-app-release.yml@main
    with:
      working-directory: .
      app-name: 'Soredowe'
      app-slug: 'soredowe'
      bin-name: 'soredowe-desktop'
      cargo-build-args: '-p app_shell'
      system-deps-linux: 'pkg-config libflatpak-dev libalpm-dev'
      os-matrix: '["ubuntu-26.04","ubuntu-26.04-arm"]'
      prerelease: ${{ inputs.mark_prerelease }}
      bump-type: ${{ inputs.bump_type }}
      generate-release-notes: true
      changelog-path: 'CHANGELOG.md'
      metainfo-path: './packaging/flathub/io.github.mlm_games.soredow.metainfo.xml'
      dispatch-on-release: '["aur-upload.yml"]'
    secrets: inherit
